variables:
  IMAGE_NAME: quay.io/kvalin/instructlab-training

build_cuda:
  image: docker:cli
  stage: build
  tags: #Need more space
    - saas-linux-medium-amd64
  services:
    - docker:dind
  before_script:
    - docker login -u=$QUAY_UNAME -p=$QUAY_PASSWD quay.io
  script:
    - docker build -t $IMAGE_NAME -f Containerfile.cuda .
    - docker push $IMAGE_NAME