on:
  push:
    branches:
      - main
jobs:
  cuda_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: kdvalin/project:latest
          file: ./Containerfile.cuda
        
