on:
  push:
    branches:
      - main
      - 'v**'
  
jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build CUDA container
      run: >
        docker build -t test:$(< ilab-version.txt)
        --build-arg="TRAINING_VERSION=$(< ilab_version.txt)"
        -f Containerfile .
      continue-on-error: true
    
    - name: Show disk space
      run: df -h && false