on:
  push:
    branches:
      - main
      - 'v**'
  
jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - name: Checkout
      uses: actions/checkout@v3

    - run: echo "TRAINING_VERSION=$([ $GITHUB_REF == "main" ] && echo 'latest' || cat ilab-version.txt)" >> $GITHUB_ENV
    
    - run: echo "TRAINING_PKG=$([ $GITHUB_REF == "main" ] && echo 'git+https://github.com/instructlab/training.git' || echo 'instructlab-training==${{env.TRAINING_VERSION}}')" >> $GITHUB_ENV
    - run: echo ${{ env.TRAINING_PKG }}

    - uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_UNAME }}
        password: ${{ secrets.QUAY_PASSWD }}

    - name: Build CUDA container
      uses: docker/build-push-action@v5
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=min
        tags: quay.io/kvalin/instructlab-training:${{env.TRAINING_VERSION}}-cuda
        file: Containerfile.cuda
        build-args: 'TRAINING_PACKAGE=${{env.TRAINING_PKG}}'
        push: true
        context: .

